### ISSUE TITLE
Overcast Not Appearing in Sonos "Add Music Services" (iOS)

### ISSUE THREAD

**Issue by michaeldupuisjr** [josh/overcast-sonos#1]
Thanks for releasing this @josh. I'm getting the "success" message after inputting my IP, but Overcast is not appearing as an available service in the Sonos app. I've closed/re-opened the app a few times and still no luck.

**Comment by ptoomey3** [comment]
Yeah, same here. I noticed that your screenshot was using Sonon 7.0.1. I also noticed that my "Add music service" menu looks a bit different than the one shown on http://overcast-sonos.herokuapp.com/setup.php. So, I took a look at the app store version history and noticed that between version 7.0.1 -> 7.1 (which is current) they note "easier music service installs". So, I wonder if this newer/easier service install somehow broke display of "side loaded" services such as this.

**Comment by Fofer** [comment]
They removed "Sonos Labs" from the iOS app.  So after following the instructions I was able to add Overcast from Sonos' desktop app instead.

**Comment by ptoomey3** [comment]
> They removed "Sonos Labs" from the iOS app. So after following the instructions I was able to add Overcast from Sonos' desktop app instead.

I totally forgot about "sonos labs" (had been a while since I added one). This totally worked..thanks!

**Comment by michaeldupuisjr** [comment]
Confirm – adding via the Sonos desktop app works.

I'll update this issue to reflect that this is only an issue with the Sonos iOS app and will defer to @josh as to whether he'd like to keep the Issue open.

**Comment by josh** [comment]
Oh!!! This makes sense. I think if we change the registration type it might show up if you don't enable Sonos Labs. One sec, I'll make a PR.

**Comment by pmarsceill** [comment]
Also having this same issue. Thanks for reporting!

**Comment by josh** [comment]
Okay, you'll have to go through the [setup page](http://overcast-sonos.herokuapp.com/setup.php) again and enter the Sonos IP again. That will register the service without the SoundLabs beta.

**Comment by pmarsceill** [comment]
I can confirm that this works on my system.  🎉
