### ISSUE TITLE
Has Sonos Update 8 broken this?

### ISSUE THREAD

**Issue by Poundsie** [josh/overcast-sonos#11]
When ever I try to follow the instructions page or use the curl command I get a 400 bad request error. Has the recent update to Sonos broken command?

**Comment by tonyrobots** [comment]
Yes, seeing the same error. 

PLAY:5: Living Room
Version: 8.0 (build 371245270)
Hardware Version: 1.13.1.8-1

**Comment by tonyrobots** [comment]
Okay, I think I've got it working. Short answer: try changing the SID to 253 (instead of 255) in the CURL string. Not sure why, but perhaps 255 is already registered on our systems?

I did a little digging and the CURL request is posting the "right answers" to this form:

http://[SONOS IP ADDRESS]:1400/customsd.htm

(Here's a [filled out version of it](https://imgur.com/5WDvmFh).)

Hopefully this helps anyone who encounters this issue...

**Comment by LonghornRach** [comment]
So I tried both 255 and 253, both gave me a internal server error (500) when the form was submitted. Filled out with same info as in your picture above @tonyrobots

**Comment by alexiscordova** [comment]
Both 255 and 253 give me a 400 Bad Request error, not 500 🤔

**Comment by tonyrobots** [comment]
Hmm, wish I could be of more help. Try SIDs ranging from 240-253, maybe one will work. Hopefully the project owner can provide more info/an update.

**Comment by drewdayton** [comment]
I tried SIDs from 240-253 so if the project owner would be able to provide an update it would be much appreciated. I am a first time Sonos owner and would love to get this working.

**Comment by alexiscordova** [comment]
@drewdayton The official tool should be updated, but this is how I got it to work in the meantime:
1. Follow the official instructions to get your Sonos IP address
2. Go to http://[Sonos IP]:1400/customsd.htm in your web browser
3. Fill out the form using @tonyrobots's example, but make the SID something other than 255 (I used 253) https://imgur.com/5WDvmFh
4. When you're done, click "Submit" and you should see the success response!

From there, you can follow the official instructions on adding the Overcast service to your Sonos.

**Comment by josh** [comment]
I just ran into this myself. It looks like 8.0 has added some additional security measures around that `/customsd.htm` setup page which breaks the automatic configuration. @alexiscordova's instructions should work as a fallback. But I'm trying to see if there's another way around it. Otherwise we'll just have to update the instructions to tell people what fields to copy.

**Comment by claytonmorrow** [comment]
Just adding on here that I setup this solution tonight using the steps from @tonyrobots and @alexiscordova - 255 and 253 failed, but 250 was success response (for me/my system).

**Comment by bleything** [comment]
@josh: I loaded the page and grabbed the `csrfToken` out of the source then added that to the args in the curl command and it worked. Should be pretty easy to automate.

**Comment by technicalpickles** [comment]
For anyone looking for something to copy & paste into the form:

- Endpoint URL: http://overcast-sonos.herokuapp.com/smapi.php
- Secure Endpoint URL: https://overcast-sonos.herokuapp.com/smapi.php
- Polling interval (seconds): 30
- Strings Table
  - Version: 1
  - Uri: http://overcast-sonos.herokuapp.com/strings.xml
- Presentation map (optional):
  - Version: 1
  - Uri: http://overcast-sonos.herokuapp.com/pmap.xml

That said, I tried both submitting the form with 250 through 250, and using the curl command with a (fresh each time) csrfToken, and got 400 Bad Request no matter what.

**Comment by bradical** [comment]
@technicalpickles or anyone else figure this out? I figured it might have to do with the URIs themselves.

**Comment by SockToy** [comment]
They've added a cross site request forgery token. Attached script solves the problem - my sonos units are registered in local dns but if you just change the list of den library, etc, for the IPs of your units it should work.
`#!/bin/ksh

for sonos in kitchen livingroom den library sewingroom office ; do
	uri="http://${sonos}:1400/customsd"
	echo
	echo Working $sonos unit
	
	echo ....getting CSRF token...
	curl --connect-timeout 5 --max-time 10 -o /tmp/fo.$$.out  "$uri.htm"
	if [ $? -gt 0 ] ; then
		echo FAIL for $sonos
		continue
	fi

	sed -e 's/^.*csrfToken" value="//' -e 's/".*$//' /tmp/fo.$$.out |&
	read -p CSRF
	rm /tmp/fo.$$.out

	echo ... token $CSRF

	curl \
	--connect-timeout 5 \
	--max-time 10 \
	--data-urlencode 'sid=255' \
	--data-urlencode 'csrfToken='"$CSRF" \
	--data-urlencode 'name=Overcast' \
	--data-urlencode 'uri=http://overcast-sonos.herokuapp.com/smapi.php' \
	--data-urlencode 'secureUri=https://overcast-sonos.herokuapp.com/smapi.php' \
	--data-urlencode 'pollInterval=30' \
	--data-urlencode 'authType=UserId' \
	--data-urlencode 'stringsVersion=1' \
	--data-urlencode 'stringsUri=http://overcast-sonos.herokuapp.com/strings.xml' \
	--data-urlencode 'presentationMapVersion=1' \
	--data-urlencode 'presentationMapUri=http://overcast-sonos.herokuapp.com/pmap.xml' \
	--data-urlencode 'containerType=MService' \
	--data-urlencode 'caps=trFavorites' \
	--data-urlencode 'caps=alFavorites' \
	--data-urlencode 'caps=logging' \
	--data-urlencode 'caps=playbackLogging' \
	--data-urlencode 'caps=extendedMD' \
	"$uri"

	echo
	echo next?
	read
done
`

**Comment by hlharrison** [comment]
Got this to work an hour ago without the script. Used SID 243 and the values in drewdayton's image. 
OSX 10.13.3
Sonos Controller for Mac 8.4
Google Chrome 65.0.3325.162
I only have a single room Sonos system (Sonos 1)

**Comment by josh** [comment]
While it's no longer a magical setup experience, the setup instructions have now been updated for manually filling out the custom service web form.

https://github.com/josh/overcast-sonos#setup

**Comment by bradical** [comment]
Works great. Thank you!
