### ISSUE TITLE
An error occurred while adding songs to the Queue (1002)

### ISSUE THREAD

**Issue by ctataryn** [josh/overcast-sonos#12]
After getting all my Overcast podcasts loaded, when I go to play an episode a "spinner" will display and then about 20 seconds later I'll get an overlay popping up that states:

> An error occurred while adding songs to the Queue (1002)

Most of the time the Sonos goes offline and needs to be manually rebooted by powering it off.

Not sure what to do at this point, I was optimistic!

Here is how I configured things:

<img width="602" alt="google chromescreensnapz007" src="https://user-images.githubusercontent.com/435719/32507086-21525650-c3ac-11e7-8741-3549d764e465.png">

P.S. I also noticed that the current song playing will sometimes get switched to something random after/during selecting an Overcast episode. Weird thing is, I got one of my episodes to finally play after multiple attempts. However if I try to go play a different episode I get the same issue.

My Sonos is a Play:1, iOS app version: `8.1.1 (build: 38946251)`. Hardware Build: `8.1 (build: 38946070)`

**Comment by ctataryn** [comment]
P.S. Tried upgrading the Hardware build to match the iOS version, but same problem occurs.

**Comment by josh** [comment]
Hey @ctataryn, thanks for opening this issue. This is something I've seen before too but I'm not exactly sure what causes it. It might be that my small Heroku instance is overloaded from all the users who use it for free. You might try deploying it to your own Heroku instance which be dedicated for your usage. Thanks!
