### ISSUE TITLE
No Playlist Support?

### ISSUE THREAD

**Issue by FalconLorenzo** [josh/overcast-sonos#13]
Does this functionality not support user-created playlists in Overcast? That seems like a significant oversight?

I followed the direction from the other thread about Sonos Update 8.0 breaking compatibility (info here: https://imgur.com/5WDvmFh) and checked "user content playlists." However, no dice. Overcast interface in the sonos app doesn't recognize any of my playlists — only view modes of all podcasts and available podcasts.

**Comment by josh** [comment]
Sorry, but the only features that are possible to support are those at are available on https://overcast.fm web player. Playlists can't be supported.
