### ISSUE TITLE
Podcast Progress Syncing

### ISSUE THREAD

**Issue by grunt121** [josh/overcast-sonos#15]
When I start a podcast that I've already partially listened to on my phone, when resuming the podcast from Sonos it starts from the begining again.

The same is true for podcasts that I start listening to on Sonsos, it doesn't sync the progress

**Comment by josh** [comment]
Hey @grunt121, I appreciate you opening this issue. This feature should generally work—but there are some known issues with some particular podcasts not reporting back a correct episode duration which prevents progress from being saved. It appears to be a limitation on the Sonos side. So I'm not sure there's anything I can do about it. Thanks for trying my side project!
