### ISSUE TITLE
Unable to browse music

### ISSUE THREAD

**Issue by sc0ttsh** [josh/overcast-sonos#16]
Hi,

I'm unable to find my podcasts through the Sonos Controller, the podcast appears and plays in the Overcast web app and iOS app but no joy with the Sonos Controller.

Apologies if this is something at my end or something that has already been covered but I couldn't find a solution when looking.

**Comment by josh** [comment]
Is the issue still happening? Sometimes those lists just cached by the Sonos app. What podcast is it? If it's an "Upload", those podcasts aren't supported.

**Comment by sc0ttsh** [comment]
Yeah Josh still happening, it's the Wrestling Observer (premium) podcast specifically however I can't get the Joe Rogan one to appear either when I put it in for testing purposes and I know that should cause me less issues. 

The podcasts will download or stream from
the app however it still says "unable to browse music" when I navigate to it through the Sonos Controller.

I downloaded the latest Joe Rogan episode and placed my phone in airplane mode and it plays without issue but still won't appear on the Sonos Controller.

**Comment by josh** [comment]
Ah, okay, it sounds like an issue with podcasts that require some kind of login. I don't think that's something Sonos can support right now. Sorry! But thanks for bringing it to my attention.
