### ISSUE TITLE
Password protected Podcasts didnt show up.

### ISSUE THREAD

**Issue by murmelbahn** [josh/overcast-sonos#24]
Hi,
I have two podcasts in my overcast which requieres authentication. Sadly they didnt show up in the Sonos App. I only have two entries named "Podcast not found"

**Comment by josh** [comment]
Yeah, sorry, but only public feeds are supported.

**Comment by eternalnewb** [comment]
Do you have any hints or ideas where to look at the code to try and figure this out? Or what makes it impractical? I could take a shot at it.
