### ISSUE TITLE
Is there a way to refresh the Podcasts list?

### ISSUE THREAD

**Issue by Chanathan** [josh/overcast-sonos#6]
I am missing episodes that were uploaded today. This service is based on the web overcast player feed right?  Let me know if there is anything I can to help.

**Comment by josh** [comment]
Like using the "Uploads" patron feature of Overcast or just a regular feed. Can you try entering the feed on this debug page and seeing if the episode ID shows up. http://overcast-sonos.herokuapp.com/debug.php

**Comment by Chanathan** [comment]
The 2 podcasts that were not showing up are showing up now. I'll have to try next time it happens. Thanks for your reply!

**Comment by josh** [comment]
Oh, awesome!
