### ISSUE TITLE
Not working with Podcasts that have chapters?

### ISSUE THREAD

**Issue by KaZaAnova** [josh/overcast-sonos#7]
I love the idea of the integration. However, it seems that it's not working with podcats that have chapter marks. I tried:
Freak Show podcast (https://freakshow.fm/podlove/file/4882/s/download/c/select-show/fs196-nickt-nicht.m4a)
Not Safe for Work Podcast https://not-safe-for-work.de/podlove/file/1852/s/download/c/select-show/nsfw097-mentalpipi.m4a

The behavior is that the podcasts show up, but when clicking them nothing happens (not even the loading circle)

Accidental Tech Podcast for example, works.

**Comment by josh** [comment]
So I don't think Sonos supports streaming `.m4a` files.

On https://sonos.custhelp.com/app/answers/detail/a_id/80/~/supported-audio-formats, only MP3 and AAC are supported under the streaming formats section.

**Comment by KaZaAnova** [comment]
Thats weird - it does work when I play m4a files from the apple podcasts app. Other people report the same here: https://en.community.sonos.com/music-services-and-sources-228994/playing-m4a-files-6739727

**Comment by heztet** [comment]
Clockwise has chapter markings, and I could play it fine: Clockwise: 192: This is Why I Left
https://overcast.fm/+DjLO3cJTg

**Comment by KaZaAnova** [comment]
did you play it on the overcast web player or through sonos? I can play all of the podcasts just fine in the web player but not through the sonos integration

**Comment by heztet** [comment]
I played it through the sonos app (iOS). I haven't tried the web player yet

**Comment by FalconLorenzo** [comment]
How do you use the Overcast webplayer to stream to sonos? Am I missing something here??

**Comment by josh** [comment]
Hey everyone, I appreciate the discussion here but I'm not sure theres anything I can change on my end. The way this works is that my service simply sends the podcast URL from the RSS feed to Sonos. The Sonos hardware is responsible for streaming/downloading and figuring out how to actually play the file. So it's really a matter of Sonos understanding the file format or not. I'm going to close out this issue as I don't think theres much I can do to help. Thanks!
