### ISSUE TITLE
We're using an old version of the Overcast app icon. 

### ISSUE THREAD

**Issue by kjellr** [josh/overcast-sonos#8]
This is very minor, but I noticed we're still pulling in an old version of the Overcast icon from the App store (it was refreshed in Overcast v3). 

Old: 
![175x175bb-old](https://cloud.githubusercontent.com/assets/1202812/25313942/710cecd2-2807-11e7-97de-b68f67a2c9e1.jpg)

New:
![175x175bb-new](https://cloud.githubusercontent.com/assets/1202812/25313945/73f42a64-2807-11e7-81e3-3741f5bc2968.jpg)

It's a quick fix: we just need to swap out the app store URLs for the icon. [This diff should take care of it.](https://gist.github.com/kjellr/77cc4af11a12a467ffd973451fd48fe3)

**Comment by josh** [comment]
Did you mean to open an issue on https://github.com/jacobian/overcast-sonos?

**Comment by kjellr** [comment]
Haha, yes I did! I guess that's what I get for following two repos with the same name. 😄

Please disregard, and sorry for the unnecessary notification ping!
