### ISSUE TITLE
Audio start incredibly slow, or skips out entirely

### ISSUE THREAD

**Issue by kylepauljohnson** [josh/overcast-sonos#9]
I was super excited to try this out, and got it setup on my home Sonos system.  I tried a handful of podcasts and one worked well.  Two others had various issues.  One a radio show from Omaha that I listen to daily took probably more than a minute or two to start.  Link to podcast below....

[Todd and Tyler Radio Empire](https://art19.com/shows/todd-n-tyler-radio-empire-podcast)

The second one I tried was the podcast S-Town by the makers of Serial.  In this case trying to play an episode and it skipped all the way through the episode list one by one quickly.  Again, podcast listed below.

[S-Town](https://stownpodcast.org/)

**Comment by josh** [comment]
I'm not really sure this a problem with the integration. overcast-sonos just sends the URL of the podcast mp3 to the sonos. Its up to your own sonos hardware and network to stream/download it. You might want to test if downloading these podcasts by hand is slow.

**Comment by kylepauljohnson** [comment]
I tried again with the radio show podcast and that worked ok upon trying
again.  The other one still never works.  Speed should be no issue.  I have
no trouble streaming anything else.  Additionally I have fiber to the home,
so I am getting 150 mbps down generally.

Kyle Johnson
206-280-1209
www.kylepauljohnson.com

**Comment by kylepauljohnson** [comment]
I will go ahead and close this issue.  Upon trying again with the radio podcast all is working as expected and I am done with the S-Town podcast at this point so I not see the issue
